export enum Types {
    ADD_TO_CART = "ADD_TO_CART",
    REMOVE_FROM_CART = "REMOVE_FROM_CART",
    LOGIN = "LOGIN",
    LOGOUT= "LOG-OUT",
    FETCH_LOGGED_IN_USER = "FETCH_LOGGED_IN_USER",
    FETCH_ITEMS_IN_CART = "FETCH_ITEMS_IN_CART"
}